account/urls.py
from django.urls import path
from account import views

app_name='account'
urlpatterns = [
  path('register/', views.register, name='register'), 
  path('login/',views.loginUser, name='login'),
  path('logout/',views.logoutUser,name='logout'),
   
]

app_film/urls.py
from django.urls import path,include
from .import views
app_name='app_film'
urlpatterns=[
    path('index/', views.IndexView.as_view(),name='index'),
    path('detail/<int:id>/',views.DetailView.as_view(),name='detail'),
    path('create-film/',views.CreateView.as_view(), name='create-film'),
]
"""www.example.com/film/detail/5"""

project_admin_film/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # why we imported static
from django.conf import settings
# app_film/hello
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app_film/', include('app_film.urls')),
    path('account/',include('account.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/app_film/', include('app_film.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/create-film.html
{% extends 'components/base.html' %}

{% block content %}
<div class="container">

    <form class="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
    <button type="submit" class="btn btn-primary mt-1">Create</button>
    </form>

</div>

{% endblock %}

templates/detail.html
{% extends 'components/base.html' %}
    
   


    {% block content %}
    <div class='container'>
    <h1>Films</h1>
    <div class="card mb-5 mx-3" style="max-width: 100%;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{{ film.poster.url }}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{film.name}}</h5>
              <p class="card-text">Rating: {{ film.rating}}</p>
              <p class="card-text"> {{ film.about}}</p>
              <p class="card-text"> {{ film.views_count}}</p>


              <p class="card-text"><small class="text-muted">Last updated {{film.pub_date}}</small></p>
              {% if request.user.is_authenticated %}
              <form method='POST'>
              {% csrf_token %}
              <input type="hidden" name="choice" value="like">
              <button type="submit" class="btn btn-primary">Like</button>
              {{film.film_likes.all | length}}
              </form>
              {% else %}
              <p><a href = "{% url 'account:login' %}">Login</a>to like</p>
              {% endif %} 
            </div>
          </div>
        </div>
      </div>
<div>
  <video width="100%" controls>
    <source src="{{ film.video.url}}" type="video/mp4">
    <source src="{{ film.video.url}}" type="video/ogg">
    Your browser does not support the video tag.
  </video>
</div>
    </div>
    <div class="container mt-3 mt-b">
    <h4> Comments ({{film.film_comments.all | length }}) </h4>
    {% for comment in film.film_comments.all %}
    <div class="card mt-1">
      <div class="card-header">
        {{ comment.user.username }}
      </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p>{{ comment.comment }}</p>
          <footer class="blockquote-footer">{{comment.pub_date}}</footer>
        </blockquote>
      </div>
    </div>
    {% endfor %}
    <form method="POST">
    {% csrf_token %}
    <input type="hidden" name="choice" value="comment">
    <div class="mb-3 mt-3">
      <label for="exampleFormControlTextarea1" class="form-label">Leave your comment</label>
      <textarea class="form-control" name="comment" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Send</button>
  </form>
 
  
    </div>
  </div>
{% endblock %}

templates/index.html
{% extends 'components/base.html'%}
{% block content %}
    <div class='container'>
    <h1>Films</h1>
<div class='container' style='display:flexbox'>
  
  {% for film in films%}
  <div class="card mb-5 mx-3" style="max-width: 540px; float:left">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="{{ film.poster.url }}" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><a href="{% url 'app_film:detail' film.id %}">{{film.name}}</a></h5>
          <p class="card-text">Rating: {{ film.rating}}</p>
          <p class="card-text">{{ film.about}}</p>

          <p class="card-text"><small class="text-muted">Last updated {{film.pub_date}}</small></p>
          

        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/login.html
      {% extends 'components/base.html' %}
      {% block content %}
      <div class="container">

        <form method="POST">
            {% csrf_token %}
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Username</label>
              <input type="text" name= "username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
              <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
           
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password</label>
              <input type="password" name= "password" class="form-control" id="exampleInputPassword1">
            </div>
         
            <button type="submit" class="btn btn-primary">Login</button>
          </form>
          {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
      </div>
  {% endblock %}
    

templates/register.html
      {% extends 'components/base.html' %}
      {% block content %}
      <div class="container">

        <form method="POST">
            {% csrf_token %}
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Username</label>
              <input type="text" name= "username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
              <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Avatar</label>
                <input type="file" name= "avatar" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <div id="emailHelp" class="form-text">We'll never share your avatar with anyone else.</div>
              </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password</label>
              <input type="password" name= "password" class="form-control" id="exampleInputPassword1">
            </div>
         
            <button type="submit" class="btn btn-primary">Submit Now</button>
          </form>
          {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
      </div>
    {% block end %}
      