account/urls.py
from django.urls import path
from account import views

app_name='account'
urlpatterns = [
  path('register/', views.register, name='register'), 
  path('login/',views.loginUser, name='login'),
  path('logout/',views.logoutUser,name='logout'),
   
]

app_film/urls.py
from django.urls import path,include
from .import views
app_name='app_film'
urlpatterns=[
    path('index/', views.IndexView.as_view(),name='index'),
    path('detail/<int:id>/',views.DetailView.as_view(),name='detail'),
    path('create-film/',views.CreateView.as_view(), name='create-film'),
]
"""www.example.com/film/detail/5"""

project_admin_film/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # why we imported static
from django.conf import settings
# app_film/hello
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app_film/', include('app_film.urls')),
    path('account/',include('account.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/app_film/', include('app_film.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
    {% include 'components/navbar.html' %}
    {% block content %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand text-light" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active text-light" aria-current="page" href="{% url 'app_film:index'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {% if request.user.is_authenticated %}
              Profile
              {% else %}
              Login/Register
              {% endif %}
            </a>
            <ul class="dropdown-menu">
            {% if request.user.is_authenticated %} <!-- 32 ve 33-cu sertde olanlarin gorunub gorunmemesi ucun-->
              <li><a class="dropdown-item" href="#">{{request.user.username}}</a></li> <!--hal hazirda login olunmus istifadeci-->
              <li><a class="dropdown-item" href="#">{{ request.user.date_joined}}</a></li> <!--hal hazirda login olunmus istifadecinin qosulma tarixi-->
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'account:login' %}">Login</a></li>
              <li><a class="dropdown-item" href="{% url 'account:register' %}">Register</a></li>
               {% endif %}
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled text-light">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success text-light" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>